-- USERS DATA
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nameFirst TEXT NOT NULL,
    nameLast TEXT NOT NULL,
    email TEXT NOT NULL,
    pass TEXT NOT NULL
);

-- DECKS DATA
CREATE TABLE IF NOT EXISTS decks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL REFERENCES users(id),
    deckName TEXT NOT NULL,
    deckDescription TEXT DEFAULT '',
);

-- CARD DATA
CREATE TABLE IF NOT EXISTS cards (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    deckId BIGINT NOT NULL REFERENCES decks(id),
    cardContent TEXT DEFAULT '',
);

-- SESSION DATA
CREATE TABLE IF NOT EXISTS userSessions (
    userId BIGINT REFERENCES users(id),
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);
